name: Safe
version: $version
main: net.milkbowl.vault.Vault
api-version: 1.13
authors: [cereal, Sleaker, mung3r, Biquaternions]
description: Drop-in Vault replacement implementing Chat, Permissions and Economy API.
website: https://serlith.net
load: STARTUP
provides: [Vault]

commands:
  vault-info:
    description: Displays information about Vault 
    usage: |
           /<command> - Displays Vault information
    permission: vault.admin
  vault-convert:
    description: Converts all data in economy1 and dumps it into economy2
    usage: |
           /<command> [economy1] [economy2]
    permission: vault.admin
permissions:
  vault.admin:
    description: Notifies the player when vault is in need of an update.
    default: op